### ISSUE TITLE
More details about the post-processing operations

### ISSUE THREAD

**Issue by MrinalJain17** [microsoft/table-transformer#10]
Hi @bsmock @rohithpv ,

This section in the paper explains the post-processing steps used at inference time.

![image](https://user-images.githubusercontent.com/19644085/141604166-b4951b89-3b03-4a9e-adf0-e574edf75fac.png)

Could you please provide some more details regarding the conflict-resolution technique used? Where can I find it in the code base?

Thanks!

**Comment by cydal** [comment]
> Hi @bsmock @rohithpv ,
> 
> This section in the paper explains the post-processing steps used at inference time.
> 
> ![image](https://user-images.githubusercontent.com/19644085/141604166-b4951b89-3b03-4a9e-adf0-e574edf75fac.png)
> 
> Could you please provide some more details regarding the conflict-resolution technique used? Where can I find it in the code base?
> 
> Thanks!

https://github.com/microsoft/table-transformer/blob/main/src/eval_utils.py

**Comment by bsmock** [comment]
Hi @MrinalJain17,

Yes, @cydal is correct, you should be able to find the relevant code here:
https://github.com/microsoft/table-transformer/blob/0aab604807fdcde12b0bf661eadf04684f0b0370/src/eval_utils.py#L74

Thanks, and let us know if you have any other questions or if we can close this issue.

**Comment by MrinalJain17** [comment]
Yes, I was able to navigate the code base. Moreover, the latest release of the paper on arXiv also had more details in this regard. Thanks!
