### ISSUE TITLE
Is it possible to build table transformer as a CoreML Model

### ISSUE THREAD

**Issue by KamranHussain05** [microsoft/table-transformer#102]
I want to use the table transformer model for a mobile App and want to see if there is support for building TableTransformer from source as a CoreML model so inferencing can be run on an iphone. Is this possible?

**Comment by KamranHussain05** [comment]
I want to use the table transformer model for a mobile App and want to see if there is support for building TableTransformer from source as a CoreML model so inferencing can be run on an iphone. Is this possible?

**Comment by ssatz** [comment]
@KamranHussain05 could you please guide me how to convert coreml models?
