### ISSUE TITLE
ICDAR-2013 dataset

### ISSUE THREAD

**Issue by punithr-vlabs** [microsoft/table-transformer#105]
Can you please provide a link to download the ICDAR-2013 dataset. I'm not able to get access for the same.

**Comment by bsmock** [comment]
Hi, apologies for not replying to this sooner.

You can find ICDAR-2013 in its original format but with our manual corrections to it here: [https://huggingface.co/datasets/bsmock/ICDAR-2013-Table-Competition-Corrected](https://huggingface.co/datasets/bsmock/ICDAR-2013-Table-Competition-Corrected)

You can find the fully-processed dataset, ICDAR-2013.c, which has both manual corrections and automated corrections, as well as rendered table images, here: [https://huggingface.co/datasets/bsmock/ICDAR-2013.c](https://huggingface.co/datasets/bsmock/ICDAR-2013.c)

Best,
Brandon
