### ISSUE TITLE
[Question] Table detection only

### ISSUE THREAD

**Issue by mineshmathew** [microsoft/table-transformer#109]
I use the inference script to perform only table detection as given below

```
python inference.py -v -p -o  --image_dir sample_image/ --out_dir  outs/ --mode detect --detection_config_path detection_config.json --detection_model_path pubtables1m_detection_detr_r18.pth --detection_device cpu
```
The script runs fine but I do not see an y results in the outs directory.

**Comment by robertoding** [comment]
I have the same issue. No cell identified.

**Comment by mineshmathew** [comment]
@robertoding You can refer to this demo  (see the app.py script) to get the detection results alone.
