### ISSUE TITLE
Not able to download pre-trained weights

### ISSUE THREAD

**Issue by amish1706** [microsoft/table-transformer#116]
I cannot download the pre-trained weights linked in the ReadMe file. It shows the following error.
![image](https://github.com/microsoft/table-transformer/assets/75967934/03ad713f-3819-4a2d-b84e-5e81377713c3)
https://pubtables1m.blob.core.windows.net/model/pubtables1m_detection_detr_r18.pth

Does anyone know how to resolve this? Are the weights hosted somewhere else?
I need these weights in order to run the inference pipeline (which can't run using the weights available on huggingface).

**Comment by bsmock** [comment]
Thanks for letting us know about this error. We are looking into what happened and will hopefully have a resolution very soon.

Best,
Brandon

**Comment by cloudfool** [comment]
I'm waiting for the model, too. Please resubmit a valid donwload url . Thanls

**Comment by cloudfool** [comment]
> I cannot download the pre-trained weights linked in the ReadMe file. It shows the following error. ![image](https://user-images.githubusercontent.com/75967934/241568894-03ad713f-3819-4a2d-b84e-5e81377713c3.png) https://pubtables1m.blob.core.windows.net/model/pubtables1m_detection_detr_r18.pth
> 
> Does anyone know how to resolve this? Are the weights hosted somewhere else? I need these weights in order to run the inference pipeline (which can't run using the weights available on huggingface).

Did you get this addressed?

**Comment by amish1706** [comment]
> Did you get this addressed?

The weights aren

I wanted to use the inference pipeline which works with the original model weights. I used HF model and then copied the important functions from the inference pipeline line to use them with HF outputs. Some small changes, and it worked.

**Comment by cloudfool** [comment]
Could you pls list the changes for me, I want to use the inference pipeline, too

**Comment by cloudfool** [comment]
> > Did you get this addressed?
> 
> The weights aren't available yet.
> 
> I wanted to use the inference pipeline which works with the original model weights. So, I used HF model and then copied the important functions from the inference pipeline line to use them with HF outputs. Some small changes, and it worked.

Could you pls list the changes for me, I want to use the inference pipeline, too

**Comment by thiagodma** [comment]
Any updates on this? Or maybe someone who already downloaded the weights could share if that's ok?

**Comment by WalidHadri-Iron** [comment]
Hi everyone,

Since this has been open for a long time, I am sharing the weights that I have downloaded before and kept locally.

For [Table Detection](https://drive.google.com/file/d/1m_vVztHZCY_9tacfITaPiLnuU_lDh-sr/view?usp=sharing)
For [Table Structure Recognition](https://drive.google.com/file/d/1jx-DBBEgKy4oCuVK_K7vCdoN6Pi3sERf/view?usp=sharing)

**Comment by bsmock** [comment]
Hi everyone,

I uploaded the weights to a new location and updated the links in the README. Please let us know if there are any issues with the new links.

Best,
Brandon

**Comment by amish1706** [comment]
> Could you pls list the changes for me, I want to use the inference pipeline, too
https://github.com/microsoft/table-transformer/issues/112#issuecomment-1600571041
Check this. Sorry for the late reply
