### ISSUE TITLE
Issues with row and cell detection (inconsistent behaviour)

### ISSUE THREAD

**Issue by mspondon** [microsoft/table-transformer#124]
I have attached the sample image from where I am interested in table , row and finally cell detection.
I am using [inference.py](https://github.com/microsoft/table-transformer/blob/main/src/inference.py) script to do the same.
I am attaching the final visualize output from the script inference.py 
![sample_page-0001](https://github.com/microsoft/table-transformer/assets/10030151/6a522214-e11e-4507-b89d-e244733ea596)
![sample_page-0001_0_fig_tables](https://github.com/microsoft/table-transformer/assets/10030151/c05f810c-7d03-4239-bfe4-5b6ef54f995a)
![sample_page-0001_0_fig_cells](https://github.com/microsoft/table-transformer/assets/10030151/50b6322c-a05b-4194-802f-7d5c617759a5)

My question is without finetuning our model , is their any way to improve that , btw thanks a lot to the community for such a wonderful model.

**Comment by bsmock** [comment]
Hi,

Sorry for the delayed response. We would expect some amount of fine-tuning of the PubTables-1M model to be needed for tables that differ from those in the PubTables-1M dataset.

However, we did just release a multi-domain pre-trained model, trained on both PubTables-1M and FinTabNet.c. You can try that model and see if your results improve on this case without doing your own fine-tuning.

Best,
Brandon

**Comment by mspondon** [comment]
@bsmock  multi-domain pre-trained model helps. Closing this.
