### ISSUE TITLE
What fraction of the test set did the model achieve perfect table (structure) recognition on? 

### ISSUE THREAD

**Issue by MrinalJain17** [microsoft/table-transformer#13]
The GriTS score provides performance estimate at the cell level. I was curious about how many of the images in the test set did the model get the table EXACTLY right.

@rohithpv @bsmock

**Comment by bsmock** [comment]
Hi, in the current version of the paper this is reported as Accuracy (AccCont) in Table 4. According to this definition of exact recognition (the text content at every grid location matches the ground truth exactly), the percentage of tables recognized exactly by the baseline DETR model in our paper is 81.38% overall, 94.68% for simple tables, and 69.44% for complex tables.

Hope that helps!

Best,
Brandon

**Comment by MrinalJain17** [comment]
Thanks @bsmock
