### ISSUE TITLE
New v1.1 TATR checkpoints are now on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [microsoft/table-transformer#158]
Hi there,

The new v1.1 TATR checkpoints are now available on Hugging Face's hub:

* https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-all
* https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-pub
* https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-fin

A demo notebook is available here which showcases detection, structure recognition and OCR: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Table%20Transformer/Inference_with_Table_Transformer_(TATR)_for_parsing_tables.ipynb.

A demo Space is available here (showcasing what's done in the notebook end-to-end): https://huggingface.co/spaces/nielsr/tatr-demo. It looks as follows:

![tatr](https://github.com/microsoft/table-transformer/assets/48327001/25ca7269-38f0-4f95-a14e-162f24c231f3)

**Comment by bsmock** [comment]
Great to see---thanks, Niels!

If anyone has a question about this, please direct it to one of the community forums on Hugging Face.

Cheers,
Brandon

**Comment by tzktok** [comment]
> Hi there,
> 
> The new v1.1 TATR checkpoints are now available on Hugging Face's hub:
> 
> * https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-all
> * https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-pub
> * https://huggingface.co/microsoft/table-transformer-structure-recognition-v1.1-fin
> 
> A demo notebook is available here which showcases detection, structure recognition and OCR: https://github.com/NielsRogge/Transformers-Tutorials/blob/master/Table%20Transformer/Inference_with_Table_Transformer_(TATR)_for_parsing_tables.ipynb.
> 
> A demo Space is available here (showcasing what's done in the notebook end-to-end): https://huggingface.co/spaces/nielsr/tatr-demo. It looks as follows:
> 
> ![tatr](https://private-user-images.githubusercontent.com/48327001/287648711-25ca7269-38f0-4f95-a14e-162f24c231f3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODM1MzMsIm5iZiI6MTcyMjU4MzIzMywicGF0aCI6Ii80ODMyNzAwMS8yODc2NDg3MTEtMjVjYTcyNjktMzhmMC00Zjk1LWExNGUtMTYyZjI0YzIzMWYzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQwNzIwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmM4YmQ5OTI2MjU0MWE4ZGE3OGU3MTA0ZDViYTVmN2E5NzZiMzE2NDA5NGViOWY0MDNhOWY1YjE0YTE1YTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n5wVvhqTmrLGcdR3PF8wr_2_T2cGTRznin3oQXzc_X8)

@NielsRogge  for  projected row headers and spanning cell it takes as row only ?
