### ISSUE TITLE
Error when running in debug mode: Runtime Error: Expected all tensors to be on the same device, but found at least 2 devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by suonbo** [microsoft/table-transformer#16]
Dear authors,
I've just implemented below code in debug mode in order to visualize reconstruction result on PDF file:

**!python main.py --data_root_dir** path/to/structure **--model_load_path** path/to/model **--table_words_dir** path/to/words **--mode** grits **--metrics_save_filepath** path/to/metrics_save_file --debug

And I experienced this bug. It says "Runtime Error: Expected all tensors to be on the same device, but found at least 2 devices, cuda:0 and cpu!
![image](https://user-images.githubusercontent.com/87938340/147814519-dd4550ac-4547-4d55-a560-cbecaf2bc9ad.png)

I implemented this on a GPU runtime of colab and this error occured. When I tried to run on CPU mode only, it said there are no GPU device.
I couldn't figure out what the reasons caused this error are. Could you help me identify where the problem is? Thanks for considering my pledge.

**Comment by bsmock** [comment]
Hi, are you using the same package versions as in our [environment file](https://github.com/microsoft/table-transformer/blob/6b61cb0ad65192b5b81bf43298e2c4ea01173bbd/environment.yml)?

**Comment by bsmock** [comment]
For reproducibility of the paper, we have to commit to certain package versions, which are provided in the environment file. Please let us know if you encounter any issues when using these.

Closing this issue but feel free to reopen if you encounter problems when using the environment that is in this repository.
