### ISSUE TITLE
Bounding box format

### ISSUE THREAD

**Issue by ksmdnl** [microsoft/table-transformer#192]
Thank you for making your work public!

I have some remarks or noticed some things regarding the format of the bounding boxes of PubMed dataset.
1. Given that the bounding boxes following Pascal VOC format, i.e. `x_min, y_min, x_max, y_max`, why does the calculation of area [here](https://github.com/microsoft/table-transformer/blob/16d124f616109746b7785f03085100f1f6247575/src/table_datasets.py#L649C41-L649C47) take the last two values? I get that it should mean calculating the width times the height but in this case these aren't it I suppose?
2. If that's the case it thus follows a wrong loss calculation shown [here](https://github.com/microsoft/table-transformer/blob/16d124f616109746b7785f03085100f1f6247575/detr/models/detr.py#L155) and [here](https://github.com/microsoft/table-transformer/blob/16d124f616109746b7785f03085100f1f6247575/detr/models/detr.py#L160-L162) as in the train mode the target is in COCO format and in the eval mode it is still in the Pascal VOC format?

Can anyone point the misunderstanding I make above or clarify?
Looking forward for the discussion!

**Comment by HenryL27** [comment]
Looks like it gets fixed in the transforms [here](https://github.com/microsoft/table-transformer/blob/16d124f616109746b7785f03085100f1f6247575/src/table_datasets.py#L227)

**Comment by HenryL27** [comment]
I commented the area line out entirely and nothing seemed to break, so I'm assuming nothing accesses that key (coco seems to do its own area calc?)

As for the format in the loss function it seems like the normalize transform converts from xyxy to cxcywh - so the loss fn can convert back properly

**Comment by ksmdnl** [comment]
It seems to be that way, though I still can't find where that is being handled.

Yes, you are correct, it's not very intuitive doing the conversion inside the normalize transform but I suppose it does the work.
Thanks for the discussion @HenryL27:)

Closing this issue for now.
