### ISSUE TITLE
Guide/Tutorial to use trained models for inference

### ISSUE THREAD

**Issue by mazharsaif** [microsoft/table-transformer#22]
Will some sample code/tutorial be available to show how to use the trained models for inference?
Also any updates on when the official trained weights will be released?

**Comment by bsmock** [comment]
A tutorial would likely come later once the code is ready for a stable release.

In the meantime, for inference questions/issues please see [#17](https://github.com/microsoft/table-transformer/issues/17).

Closing this issue as a duplicate.

Best,
Brandon

**Comment by vaibhavkansallumiq** [comment]
> A tutorial would likely come later once the code is ready for a stable release.
> 
> In the meantime, for inference questions/issues please see [#17](https://github.com/microsoft/table-transformer/issues/17).
> 
> Closing this issue as a duplicate.
> 
> Best, Brandon

when it would like to come
