### ISSUE TITLE
How to develop my own datasets according to your methods?

### ISSUE THREAD

**Issue by FaltingsA** [microsoft/table-transformer#25]
Hi authors,
Thanks for your great work! I want to develop a program to generate my own TSR datasets from word file. But I don't have enough experience to do it.  So，I want to ask you for help to develop my own datasets. It would be appreciated if you  canrelease the program code about the process to develop PubTables-1M or offer any other help. Thanks you again!

**Comment by AICampB4** [comment]
Hi, I have developed my own dataset for this task. We just used the default configuration of LablImg tool to label for data. It is very simple to use

**Comment by hmtrii** [comment]
Hi @AICampB4, could you tell me the size of your dataset and the performance of the proposed method? BTW, which type of your dataset? Is this pdf papers?

**Comment by AICampB4** [comment]
> Hi @AICampB4, could you tell me the size of your dataset and the performance of the proposed method? BTW, which type of your dataset? Is this pdf papers?

The size of dataset is 20K table images (for structure recognition tasks). We generated them by a tool we built based on opencv. We have been trying to use transfer learning in order to make the model fit to the distribution of the new data. The initial result is not accurate as we wish, but it shows some positive output that it fits to the new data better than the original model trained on pubtables-1M data only.

**Comment by samiptimalsena** [comment]
Hi @AICampB4, I need to train the model in my custom dataset. I created the dataset in Pascal-VOC format, but there seems to be some directory structure issues. Can you please highlight me the directory structure you have in your custom data?

**Comment by jigsawcoder** [comment]
> Hi @AICampB4, I need to train the model in my custom dataset. I created the dataset in Pascal-VOC format, but there seems to be some directory structure issues. Can you please highlight me the directory structure you have in your custom data?

Have successfully trained the model using your own dataset? 
If yes, then please let me know which object detection format you have used (COCO or Pascal-VOC) and in which directory have you kept the data?
