### ISSUE TITLE
Wrong check of torchvision version in detr.util.misc.py

### ISSUE THREAD

**Issue by plopd** [microsoft/table-transformer#26]
The version check [here](https://github.com/microsoft/table-transformer/blob/9c66c865afa1bdc6da499e0076140ec16d11aa9b/detr/util/misc.py#L21) fails for `torchvision.__version__ == '0.11.2'` because it is wrongly comparing `0.1 < 0.7`. Instead the comparison should be `0.11 < 0.7`.

Note that a correct implementation should also consider cases like `0.4.2.post2`.

**Comment by plopd** [comment]
I think this should fix the issue.

`f = lambda x: float("".join(x.split(".",)[1:3]))`

**Comment by bsmock** [comment]
Thank you, we have now adopted the fix from the original DETR codebase. It will be in the next pull request.
