### ISSUE TITLE
data error

### ISSUE THREAD

**Issue by yang-chenyu104** [microsoft/table-transformer#36]
in the Image_Table_Structure_PASCAL_VOC.tar.gz,there is no val and test data.only train data in the zip.

**Comment by bsmock** [comment]
I think we were finally able to reproduce the error you encountered.

The PASCAL VOC archives should contain four folders: images, train, test, and val.

We tried unzipping "PubTables-1M-Image_Page_Detection_PASCAL_VOC.tar.gz" on a Linux machine with fewer resources than our normal machines and it completed without producing the "val" and "test" folders just as you experienced.

However, then we tried unzipping the archive a second time and that time it successfully produced all four folders.

Can you try again and let us know if you were eventually successful?

We will update the documentation for the data to make sure everyone can verify all of the data is present when they unzip.

If there are still issues unzipping the data we'll look into possibilities for structuring the data into smaller archives.

**Comment by yang-chenyu104** [comment]
yes,when i try again unzip the documentation,i look all the folders,thank you very much,come on together




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Brandon ***@***.***&gt;; 
发送时间: 2022年5月13日(星期五) 凌晨1:26
收件人: ***@***.***&gt;; 
抄送: "な法--言说 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/table-transformer] data error (Issue #36)





 
I think we were finally able to reproduce the error you encountered.
 
The PASCAL VOC archives should contain four folders: images, train, test, and val.
 
We tried unzipping "PubTables-1M-Image_Page_Detection_PASCAL_VOC.tar.gz" on a Linux machine with fewer resources than our normal machines and it completed without producing the "val" and "test" folders just as you experienced.
 
However, then we tried unzipping the archive a second time and that time it successfully produced all four folders.
 
Can you try again and let us know if you were eventually successful?
 
We will update the documentation for the data to make sure everyone can verify all of the data is present when they unzip.
 
If there are still issues unzipping the data we'll look into possibilities for structuring the data into smaller archives.
