### ISSUE TITLE
The dataset home page is not working

### ISSUE THREAD

**Issue by narthchin** [microsoft/table-transformer#55]
The website kept saying that "Loading Dataset Details..." and it didn't return with anything after waiting for a long time. Another weird problem is that I cann't see any dataset or use the search function in msropendata.com. I tried to file a issue in msropendata.com, but it can not be submitted. Is the backend server of msropendata down or something else?
Thanks for your help!

**Comment by bsmock** [comment]
Hi, I just tried it and it's working now. Hopefully it was just a temporary issue and you're able to access the data.

Cheers,
Brandon

**Comment by narthchin** [comment]
Thanks for your reply! I re-checked this and it seems to be caused by my browser's content blocker...
If any guys runs into the same issue like this, consider disabling the content blocker or cookie blocker and things will get work.

Cheers,
Narth
