### ISSUE TITLE
about the annotation tool

### ISSUE THREAD

**Issue by ZhenhuaTian** [microsoft/table-transformer#62]
Could you please release the annotation tool for 1M-PubTables too?

**Comment by LxYuan-Handshakes** [comment]
+1 

Hi @bsmock,  
Is it possible to share the annotation tool for us to annotate our own custom dataset?

Thanks.

**Comment by bsmock** [comment]
We are actively working on releasing much of the data processing code. But the first version is likely to assume you already have an HTML for the table and bounding boxes for the text in every cell (like datasets such as ICDAR-2013, PubTables-1M and FinTabNet provide). The code would canonicalize this data, make bounding boxes for rows and columns, and put it into the format this repository expects for training. Is that what you're looking for?

**Comment by nikithakriz** [comment]
Hai, shall we use LabelIMG's PASCAL-VOC format type annotated data to finetune the table transformer?

**Comment by abhayhk2001** [comment]
Hi, if its possible can you share the annotation tool with us.
We are trying to fine tune the model for a custom dataset.

Tagging @bsmock  for visibility
