### ISSUE TITLE
structure recognition results from the provided weight are weird

### ISSUE THREAD

**Issue by ejlee95** [microsoft/table-transformer#65]
Hi, thanks for releasing the data, codes and weights!

But when I ran the TSR inference code with the provided weight on the PubTables1M dataset,
it gives me no-object table objects on almost all tables like this:
(gray boxes are no-object boxes)
![그림1](https://user-images.githubusercontent.com/36064879/184298662-3763f683-6bee-478f-b971-56adb2a449cc.png)

I tested on docker and created a conda environment using the provided yml file.

Any suggestions..?

**Comment by ejlee95** [comment]
I re-installed the packages, and it worked!

**Comment by vaibhavkansallumiq** [comment]
can you share the inference code
