### ISSUE TITLE
Fine-tune the table-transformer model.

### ISSUE THREAD

**Issue by vallabh001** [microsoft/table-transformer#70]
I'm new to this field and I was wondering if someone could help me with a question. I wanted to know how to annotate the images and fine-tune the Microsoft-table transformer model for a custom dataset.

Thank you so much in advance.

**Comment by light42** [comment]
How to fine-tune the model is in README, and I think it's clear enough. But I agree that the details for making your custom dataset is confusing.

**Comment by vaibhavkansallumiq** [comment]
@light42 i have fine tuned my TD model and i saved my  , i want a simple inference script to test it on single image
can you please help ?
