### ISSUE TITLE
ModuleNotFoundError: No module named 'engine'

### ISSUE THREAD

**Issue by zanvari** [microsoft/table-transformer#73]
I tried the detection model evaluation code and I get the "from engine import evaluate, train_one_epoch ModuleNotFoundError: No module named 'engine''" error. I wonder how that can be fixed?

**Comment by Siddhu2502** [comment]
i am trying to parse pdf pages convert them to images and then detect tables and extract them and i cant just work with command line hence what am i supposed to do even after downloading the package and CDing into the src folder i tried to create a new file and wrote my code yet the same problem 

tried to apped sys.path.apped and still did not succeed
