### ISSUE TITLE
Single Inference of TSR

### ISSUE THREAD

**Issue by emigomez** [microsoft/table-transformer#83]
Hi!

I want to run the whole pipeline of TSR for a single input image obtaining as output the final data frame result.
I think that the deployment to obtain this final data frame is implemented here as 'functional analysis', but the problem is that I don't know how to make a **single image inference with this repo.**

Do you know how to run a single image inference of the entire TSR+funtional analysis pipeline? (I read similar issues but don't find the solution)

Regards

**Comment by vaibhavkansallumiq** [comment]
did you find Single Inference of TDR
