### ISSUE TITLE
FinTabNet

### ISSUE THREAD

**Issue by talhalpern10** [microsoft/table-transformer#89]
Hi, I want to test the checkpoint of fintabnet and after do train on it and retest. What is the best way to do it?  Also, will you share the concatenation tool? I think you also have a tool to fix some tagging issues with oversplitting? Thx

**Comment by bsmock** [comment]
Hi, several months ago we started to release code for processing FinTabNet but from a research standpoint we decided it needed a little more work to get right. This is a research codebase and unfortunately once a research artifact is released it can be difficult to update it. People may have already started building new research on what you released, so you can really only justify major updates after that point.

The good news I think pretty soon we can officially release code to process FinTabNet according to our methods. Stay tuned, more updates are coming.
