### ISSUE TITLE
Definition of GriTS

### ISSUE THREAD

**Issue by cpwan** [microsoft/table-transformer#9]
In the paper, the GriTS is defined as the fraction of inverses. I doubt its validity. 

1. If A and B are very dissimilar, they can get f(...) = 0 for every cell. Then, the numerator would be undefined. 
2. Follow from 1, dissimilar table can get a higher GriTS than similar table. If so, calling GriTS  a 'similarity' seems weird.
3. If GriTS-Recall= f(...)/|A|, GriTS-Precision=f(...)/|B|, then the F-score should be 2/(recall^-1+precision^-1)=2/(|A|/f(...)+|B|/f(...))=2f(...)/(|A|+|B|). 

Hence, I doubt that the inverse should not be taken in the definition. How is that implemented in the code?

![image](https://user-images.githubusercontent.com/22132868/139655360-f6545f24-6b71-4393-aed5-47b96d936769.png)

**Comment by bsmock** [comment]
I'm closing this issue as the newest version of the paper for PubTables-1M has the correct definition. The full paper for GriTS will be released soon.

Best,
Brandon
