### ISSUE TITLE
Is this available with instance segmentation task?

### ISSUE THREAD

**Issue by yellowjs0304** [microsoft/table-transformer#92]
Hi, I hope to train the TSR components by instance segmentation task.

This model is using the DETR, and DETR also support instance(panoptic) segmentation task.

Is there any option or comment should i modify for segmentation task?

**Comment by bsmock** [comment]
Hi, the DETR code has a segmentation option but we have not tried it on this task so unfortunately we really can't provide any guidance here

**Comment by yellowjs0304** [comment]
Thanks.
